package ai.or4cl3.meridian.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import java.util.UUID

/**
 * PRAXIS Alert Node
 *
 * Generated by PRAXIS when trigger conditions are met.
 * Stores the full reasoning chain (thinkingOutput) so the farmer
 * sees not just the recommendation but exactly why it was generated.
 */
@Entity(
    tableName = "praxis_alerts",
    indices = [Index("alertType"), Index("generatedAt"), Index("isRead"), Index("isResolved")]
)
data class PraxisAlert(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val alertType: AlertType,
    val severity: AlertSeverity,
    val title: String,
    val summary: String,
    // Full PRAXIS thinking mode output — the complete reasoning chain
    val thinkingOutput: String,
    // Structured options generated by PRAXIS
    val optionsJson: String, // JSON array of ActionOption
    val triggeringObservationIds: String = "", // JSON array of observation IDs
    val triggeringPlaceIds: String = "", // JSON array of place IDs
    val generatedAt: Long = System.currentTimeMillis(),
    val expiresAt: Long? = null,
    val isRead: Boolean = false,
    val isResolved: Boolean = false,
    val linkedInterventionId: String? = null,
    // Source metadata
    val sourceType: AlertSourceType = AlertSourceType.LOCAL,
    val psalMeshCommunityId: String? = null // set if from PSALM regional intelligence
)

enum class AlertType {
    THRESHOLD, // indicator crossed critical boundary
    PATTERN_DIVERGENCE, // current season deviating from historical
    REGIONAL_INTELLIGENCE, // incoming from PSALM mesh
    OPPORTUNITY, // favorable conditions for intervention
    STRATEGIC // longer-horizon farming system guidance
}

enum class AlertSeverity {
    INFO, WARNING, URGENT, CRITICAL
}

enum class AlertSourceType {
    LOCAL, PSALM_MESH, REGIONAL_HUB
}

/** A single actionable option generated by PRAXIS within an alert */
data class ActionOption(
    val tier: String, // "optimal", "achievable", "minimal"
    val title: String,
    val description: String,
    val resourcesRequired: List<String>,
    val estimatedCost: String,
    val estimatedOutcome: String,
    val confidenceScore: Float
)
